# Generated by Django 4.1.5 on 2023-01-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mbsite/')),
                ('headding', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('description_icon', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Mysilf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=500)),
                ('percentage', models.IntegerField()),
                ('typ', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO')], max_length=20)),
            ],
        ),
    ]
