# Generated by Django 4.1.5 on 2023-01-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbsite', '0002_education_experience_portfolio_services_sumary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysilf',
            old_name='age',
            new_name='job',
        ),
    ]
