# Generated by Django 4.1.5 on 2023-01-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbsite', '0004_sumary_point2_sumary_point3'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='point1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='point2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='point3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='point4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
