# Generated by Django 4.1.5 on 2023-01-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbsite', '0005_experience_point1_experience_point2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='point1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='point2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='point3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='point4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
