# Generated by Django 4.1.5 on 2023-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbsite', '0006_education_point1_education_point2_education_point3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=100)),
                ('point1', models.CharField(max_length=100)),
                ('point2', models.CharField(max_length=100)),
                ('point3', models.CharField(max_length=100)),
                ('point4', models.CharField(max_length=100)),
            ],
        ),
    ]
